/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:col_slider:546561:
//  colNum = col_slider.getValueI();
} //_CODE_:col_slider:546561:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  col_slider = new GCustomSlider(this, 900, 0, 100, 40, "grey_blue");
  col_slider.setLimits(3.0, 3.0, 5.0);
  col_slider.setNumberFormat(G4P.DECIMAL, 2);
  col_slider.setOpaque(false);
  col_slider.addEventHandler(this, "custom_slider1_change1");
}

// Variable declarations 
// autogenerated do not edit
GCustomSlider col_slider; 
